# Generated by Django 4.2 on 2023-04-09 05:54

from django.db import migrations, models
import django.db.models.deletion
import sitiosApp.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Provincia',
            fields=[
                ('id', models.CharField(default=sitiosApp.models.generate_primary_key, max_length=40, primary_key=True, serialize=False, unique=True)),
                ('codigo', models.CharField(max_length=5, unique=True)),
                ('nombre', models.CharField(max_length=25, unique=True)),
            ],
            options={
                'ordering': ('codigo',),
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='TipoSitio',
            fields=[
                ('id', models.CharField(default=sitiosApp.models.generate_primary_key, max_length=40, primary_key=True, serialize=False, unique=True)),
                ('nombre', models.CharField(max_length=25, unique=True)),
            ],
            options={
                'ordering': ('nombre',),
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Sitio',
            fields=[
                ('id', models.CharField(default=sitiosApp.models.generate_primary_key, max_length=40, primary_key=True, serialize=False, unique=True)),
                ('nombre', models.CharField(max_length=25, unique=True)),
                ('direccion', models.CharField(blank=True, max_length=100)),
                ('capacidad', models.IntegerField(default=0)),
                ('fechaApertura', models.DateField()),
                ('disponible', models.BooleanField()),
                ('foto', models.ImageField(upload_to='sitiosMedia')),
                ('provincia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sitiosApp.provincia')),
                ('tipo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sitiosApp.tipositio')),
            ],
            options={
                'ordering': ('nombre',),
                'abstract': False,
            },
        ),
    ]
