# Generated by Django 4.2 on 2023-04-09 07:24

from django.db import migrations, models
import django.db.models.deletion
import sitiosApp.models


class Migration(migrations.Migration):

    dependencies = [
        ('sitiosApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='provincia',
            name='codigo',
            field=models.CharField(max_length=5, unique=True, verbose_name='Código'),
        ),
        migrations.AlterField(
            model_name='provincia',
            name='id',
            field=models.CharField(default=sitiosApp.models.generate_primary_key, max_length=40, primary_key=True, serialize=False, unique=True, verbose_name='Id'),
        ),
        migrations.AlterField(
            model_name='provincia',
            name='nombre',
            field=models.CharField(max_length=25, unique=True, verbose_name='Nombre'),
        ),
        migrations.AlterField(
            model_name='sitio',
            name='capacidad',
            field=models.IntegerField(default=0, verbose_name='Capacidad'),
        ),
        migrations.AlterField(
            model_name='sitio',
            name='direccion',
            field=models.CharField(blank=True, max_length=100, verbose_name='Dirección'),
        ),
        migrations.AlterField(
            model_name='sitio',
            name='disponible',
            field=models.BooleanField(verbose_name='Disponible'),
        ),
        migrations.AlterField(
            model_name='sitio',
            name='fechaApertura',
            field=models.DateField(verbose_name='Fecha Apertura'),
        ),
        migrations.AlterField(
            model_name='sitio',
            name='foto',
            field=models.ImageField(upload_to='sitiosMedia', verbose_name='Foto'),
        ),
        migrations.AlterField(
            model_name='sitio',
            name='id',
            field=models.CharField(default=sitiosApp.models.generate_primary_key, max_length=40, primary_key=True, serialize=False, unique=True, verbose_name='Id'),
        ),
        migrations.AlterField(
            model_name='sitio',
            name='nombre',
            field=models.CharField(max_length=25, unique=True, verbose_name='Nombre'),
        ),
        migrations.AlterField(
            model_name='sitio',
            name='provincia',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sitiosApp.provincia', verbose_name='Provincia'),
        ),
        migrations.AlterField(
            model_name='sitio',
            name='tipo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sitiosApp.tipositio', verbose_name='Tipo'),
        ),
        migrations.AlterField(
            model_name='tipositio',
            name='id',
            field=models.CharField(default=sitiosApp.models.generate_primary_key, max_length=40, primary_key=True, serialize=False, unique=True, verbose_name='Id'),
        ),
        migrations.AlterField(
            model_name='tipositio',
            name='nombre',
            field=models.CharField(max_length=25, unique=True, verbose_name='Nombre'),
        ),
    ]
