# Generated by Django 4.2 on 2023-04-10 03:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sitiosApp', '0002_alter_provincia_codigo_alter_provincia_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sitio',
            name='disponible',
            field=models.BooleanField(default=True, verbose_name='Disponible'),
        ),
    ]
