# Generated by Django 4.2 on 2023-04-10 04:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sitiosApp', '0003_alter_sitio_disponible'),
    ]

    operations = [
        migrations.AlterField(
            model_name='provincia',
            name='id',
            field=models.UUIDField(default='f47f0e7563aa45bb89baa07dfab0506c', editable=False, primary_key=True, serialize=False, unique=True, verbose_name='Id'),
        ),
        migrations.AlterField(
            model_name='sitio',
            name='fechaApertura',
            field=models.DateField(help_text='Por favor use el formato: <em>MM/DD/YYYY</em>.', verbose_name='Fecha Apertura'),
        ),
        migrations.AlterField(
            model_name='sitio',
            name='foto',
            field=models.ImageField(max_length=255, upload_to='sitiosMedia', verbose_name='Foto'),
        ),
        migrations.AlterField(
            model_name='sitio',
            name='id',
            field=models.UUIDField(default='f47f0e7563aa45bb89baa07dfab0506c', editable=False, primary_key=True, serialize=False, unique=True, verbose_name='Id'),
        ),
        migrations.AlterField(
            model_name='tipositio',
            name='id',
            field=models.UUIDField(default='f47f0e7563aa45bb89baa07dfab0506c', editable=False, primary_key=True, serialize=False, unique=True, verbose_name='Id'),
        ),
    ]
