# Generated by Django 4.2 on 2023-04-10 04:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sitiosApp', '0004_alter_provincia_id_alter_sitio_fechaapertura_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='provincia',
            name='id',
            field=models.UUIDField(default='11d83ea9c7134397840d7f2cdc5210c2', editable=False, primary_key=True, serialize=False, unique=True, verbose_name='Id'),
        ),
        migrations.AlterField(
            model_name='sitio',
            name='id',
            field=models.UUIDField(default='11d83ea9c7134397840d7f2cdc5210c2', editable=False, primary_key=True, serialize=False, unique=True, verbose_name='Id'),
        ),
        migrations.AlterField(
            model_name='tipositio',
            name='id',
            field=models.UUIDField(default='11d83ea9c7134397840d7f2cdc5210c2', editable=False, primary_key=True, serialize=False, unique=True, verbose_name='Id'),
        ),
    ]
