# Generated by Django 4.2 on 2023-04-10 04:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sitiosApp', '0007_alter_provincia_id_alter_sitio_id_alter_tipositio_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sitio',
            name='foto',
            field=models.ImageField(max_length=255, null=True, upload_to='sitiosMedia', verbose_name='Foto'),
        ),
    ]
