# Generated by Django 4.2 on 2023-04-10 05:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sitiosApp', '0008_alter_sitio_foto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sitio',
            name='foto',
            field=models.ImageField(blank=True, max_length=255, upload_to='sitiosMedia', verbose_name='Foto'),
        ),
    ]
